services:
  mysql:
    image: mysql
    restart: on-failure:3
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  tao-api:
    build:
      context: ./tao-api
    restart: on-failure:3
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - tao-api:/app/data
volumes:
  mysql:
  tao-api: