services:
  mysql:
    image: mysql
    restart: on-failure:3
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql: