services:
  # mysql:
  #   image: mysql
  #   restart: on-failure:3
  #   env_file:
  #     - .env
  #   expose:
  #     - "3306"
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

  redis:
    image: redis
    restart: on-failure:3
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  worker:
    build:
      context: ./tao-api
    command: celery -A tao_celery worker --loglevel=info --uid=taoapi
    restart: on-failure:3
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
        
  tao-api:
    build:
      context: ./tao-api
    restart: on-failure:3
    env_file:
      - .env
    depends_on:
    #   mysql:
    #     condition: service_healthy
        redis:
          condition: service_healthy
        worker:
          condition: service_started
    volumes:
      - tao-api:/app/data
      - ./wallets:/app/wallets
    ports:
      - "8000:8000"
volumes:
  # mysql:
  tao-api: